server { listen 80; server_name _; root /usr/share/nginx/html; index index.html;
 location / { try_files $uri /index.html; }
 location /api/courses { proxy_pass http://course-service:8081/api/courses; }
 location /api/students { proxy_pass http://student-service:8082/api/students; }
}
